#pragma once
//#define ADD   
//#define	ADC  
//#define	ADIW
//#define	SUB 
//#define	SUBI
//#define	SBC 
//#define	SBCI
//#define	SBIW
//#define	AND 
//#define	ANDI
//#define	OR 
//#define	ORI 
//#define	EOR 
//#define	COM 
//#define	NEG 
//#define	SBR 
//#define	CBR 
//#define	INC 
//#define	DEC 
//#define	TST 
//#define	CLR 
//#define	SER 
//#define	MUL 
//#define	MULS
//#define	MULS
//#define	FMUL
//#define	FMUL
//#define	FMUL
//#define	RJMP
//#define	IJMP
//#define	EIJM
//#define	JMP 
//#define	RCAL
//#define	ICAL
//#define	EICA
//#define	CALL
//#define	RET 
//#define	RETI
//#define	CPSE
//#define	CP
//#define	CPC 
//#define	CPI 
//#define	SBRC
//#define	SBRS
//#define	SBIC
//#define	SBIS
//#define	BRBS
//#define	BRBC
//#define	BREQ
//#define	BRNE
//#define	BRCS
//#define	BRCC
//#define	BRSH
//#define	BRLO
//#define	BRMI
//#define	BRPL
//#define	BRGE
//#define	BRLT
//#define	BRHS
//#define	BRHC
//#define	BRTS
//#define	BRTC
//#define	BRVS
//#define	BRVC
//#define	BRIE
//#define	MOV 
//#define	MOVW
//#define	LDI 
//#define	LDS 
//#define	LD 
//#define	LD 
//#define	LD 
//#define	LD 
//#define	LD 
//#define	LD 
//#define	LDD 
//#define	LD 
//#define	LD 
//#define	LD 
//#define	LDD 
//#define	STS 
//#define	ST 
//#define	ST 
//#define	ST 
//#define	ST 
//#define	ST 
//#define	ST 
//#define	STD 
//#define	ST 
//#define	ST 
//#define	ST 
//#define	STD 
//#define	LPM 
//#define	LPM 
//#define	LPM 
//#define	ELPM
//#define	ELPM
//#define	ELPM
//#define	SPM 
//#define	IN
//#define	OUT 
//#define	PUSH
//#define	POP 
//#define	Bit 
//#define	LSL 
//#define	LSR 
//#define	ROL 
//#define	ROR 
//#define	ASR 
//#define	SWAP
//#define	BSET
//#define	BCLR
//#define	SBI 
//#define	CBI 
//#define	BST 
//#define	BLD 
//#define	SEC 
//#define	CLC 
//#define	SEN 
//#define	CLN 
//#define	SEZ 
//#define	CLZ 
//#define	SEI 
//#define	CLI 
//#define	SES 
//#define	CLS 
//#define	SEV 
//#define	CLV 
//#define	SET 
//#define	CLT 
//#define	SEH 
//#define	CLH 
//#define BREAK
#define NOP 0x0000
#define SLEEP 0x9588
//#define WDR